import torch

PAD_TOKEN = 53
CHECKPOINT_DIR = "./checkpoint"

BATCH_SIZE = 32
NUM_WORKERS = 8

LEARNING_RATE = 1e-5
WEIGHT_DECAY = 5e-4
ADAM_EPS = 5e-9
SCHEDULER_FACTOR = 0.9
SCHEDULER_PATIENCE = 10

DROPOUT_RATE = 0.1